AC-7073 :: Calendar picker for individual office hours holder availability
masschallenge/calendar-module pull request #1
Opened 2019-11-16 02:45 UTC by freshprincekla

### Changes introduced in: [AC-7073](https://masschallenge.atlassian.net/browse/AC-7073):
- Add a calendar picker for individual office hours holder availability
### How to test
- Checkout this branch on `accelerate, impact and frontend`
- On localhost
- Navigate to this mentor's office hours [page](http://localhost:8181/officehours/bos/2019/?mentor_id=59788) and schedule office hours on his behalf.
- Masquerade as this [finalist](http://localhost:8181/admin/simpleuser/user/13884/masquerade/)
- Visit http://localhost:1234/directory/people/56778
- Click the `Available Office Hours` button
- See that a modal show up with the calendar.
- Follow the mockups attached on this ticket and ensure that the feature works as required.

2019-11-20 14:48 UTC, hfreund requested changes
Left comments about how to modify the CSS to resolve 2 issues:

1. Stretched circles should be round and centered in their container
2. Stacked items should be aligned horizontally and vertically in such a way that similar items below them are likewise horizontally and vertically aligned and therefore totally obscured

Result should look something like this *note that where colors differ from the mockup, mockup should prevail:
![image](https://user-images.githubusercontent.com/11574697/69248771-e0950680-0b7a-11ea-9034-0c95cdb04f30.png)

2019-11-20 14:48 UTC, hfreund commented on examples/styles.scss
> +$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/' !default;
Do we need to import all of these styles? It seems like importing all of Bootstrap is just going to add a lot of bloat we don't want. Does it make more sense to spend some extra effort now to write our own CSS for the calendar that is in line with Semantic, since we'll be overriding any Bootstrap styling anyway?

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +  overflow: hidden; }
add:
`justify-content: space-evenly;`

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +  flex: 1 0 0%; }
add:
```
max-width: 36px;
height: 36px;
```

2019-11-20 14:48 UTC, hfreund commented on src/sass/styles.scss
> +  border-radius: 100%;
`border-radius: 50%`

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +  flex-direction: row; }
add:
`justify-content: space-evenly;`

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +  margin-top: 2.2%; }
Delete `line-height` and `margin-top`
Add:
```
max-width: 36px;
height: 36px;
display: flex;
align-items: center;
justify-content: center;
padding-bottom: 1px;
```

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +  padding: 6px 0px;
Delete `padding`

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +  width: 37px; }
Change `width: 36px;`
Add
```
height: 36px;
display: flex;
align-items: center;
justify-content: center;
```

2019-11-20 14:48 UTC, hfreund commented on lib/css/react-big-calendar.css
> +    font-size: 16px; }
Change/add:
```
font-weight: 700;
font-size: 13px;
padding-bottom: 1px;
```

2019-11-25 14:48 UTC, mkiterian requested changes
~couldn't trace it but there's an errant `console.log`~ resolved

2019-11-25 15:00 UTC, mkiterian commented
<img width="474" alt="Screenshot 2019-11-25 at 17 58 34" src="https://user-images.githubusercontent.com/13675851/69551191-5818ca80-0fad-11ea-88f3-4b002f63e7cf.png">

The dates with office hours are duplicated and overlapping

2019-11-25 18:08 UTC, hfreund approved these changes
Looks good from UX

2019-11-27 17:23 UTC, shakirandagire approved these changes
The QA looks good.
- I have masqueraded as a mentor with available office hours.
- Have clicked on the calendar dates on which they are available for office hours.
- The office hours are filtered by the selected calendar date.

2019-11-27 18:36 UTC, mkiterian approved these changes
Code changes look good

2019-11-28 03:20 UTC, merged